### ISSUE TITLE
README says binaries available but are not

### ISSUE THREAD

**Issue by chipzoller** [google/container-explorer#10]

**Comment by roshanmaskey** [comment]
The latest binary is in the release section https://github.com/google/container-explorer/releases/tag/0.0.6..

You can also install it on a Linux system by running the [setup script](https://github.com/google/container-explorer/blob/main/script/setup.sh).

```
$ wget https://github.com/google/container-explorer/blob/main/script/setup.sh
$ sudo bash setup.sh install
```

This will install the binary and supporting files to `/opt/container-explorer`.

**Comment by roshanmaskey** [comment]
I have added installation instructions at https://github.com/google/container-explorer#installing-container-explorer.

**Comment by chipzoller** [comment]
My apologies. I interpreted the tar.gz file as the source tarball.
